### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by maddawik** [vulncheck-oss/sdk-python#4]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by tcampbPPU** [comment]
I have a few over in the Go SDK, maybe we can try to keep them similar? 
https://github.com/vulncheck-oss/sdk-go/tree/main/.github/ISSUE_TEMPLATE

**Comment by maddawik** [comment]
> I have a few over in the Go SDK, maybe we can try to keep them similar? https://github.com/vulncheck-oss/sdk-go/tree/main/.github/ISSUE_TEMPLATE

Good call! Thanks for mentioning it, I'll add them here too
